### ISSUE TITLE
npm start ne fonctionne pas 

### ISSUE THREAD

**Issue by JeepDrummer** [RobinLebhar/ReactRedux-Starter#2]
Bonjour, quand je lance la commande` npm start ` le projet ne se lance pas et voici l'erreur qui apparaît dans le terminal...
```
 const webpackConfigurationValidationErrors = validateSchema(
                                                             ^

TypeError: validateSchema is not a function
    at processConfiguredOptions (C:\DevJeep\Formation\React\Udemy\ReactRedux-Starter\node_modules\webpack-cli\bin\convert-argv.js:156:48)
    at module.exports (C:\DevJeep\Formation\React\Udemy\ReactRedux-Starter\node_modules\webpack-cli\bin\convert-argv.js:150:10)
    at Object.<anonymous> (C:\DevJeep\Formation\React\Udemy\ReactRedux-Starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js:234:54)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-redux-pack-demarrage@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-pack-demarrage@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kodakodu** [comment]
Bonjour
Avez vous trouvé une solution ?

**Comment by Solweigdev** [comment]
[Resolve issue here](https://stackoverflow.com/questions/49071702/webpack-validateschema-is-not-a-function-error-in-survivejs)
